title: Daylin's Brain Dump
baseUrl: https://brain.dayl.in/
contentDir: ../slipbox/
enableGitInfo: true

module:
  imports:
  - path: github.com/daylinmorgan/brain-stem

markup:
  highlight:
    style: catppuccin-mocha
