title: Daylin's Brain Dump
contentDir: ../slipbox/
theme: brain-stem
enableGitInfo: true

module:
  imports:
  - path: github.com/daylinmorgan/brain-stem

markup:
  highlight:
    style: catppuccin-mocha
