$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
dictionaryDefinitions:
  - name: dict
    path: './dict.txt'
    addWords: true
dictionaries:
  - dict
ignorePaths:
  - 'node_modules'
  - '/dict.txt'

